import { createNewPickup } from '../../app/common/util/helpers';
import moment from 'moment';

export const createPickup = pickup => {
  return async (dispatch, getState, { getFirestore }) => {
    const firestore = getFirestore();
    const user = firestore.auth().currentUser;
    const photoURL = getState().firebase.profile.photoURL;
    let newPickup = createNewPickup(user, photoURL, pickup);
    try {
      let createdPickup = await firestore.add(`pickups`, newPickup); // adds new pickup doc to pickups collection with autogenerated id
      await firestore.set(`pickup_attendee/${createdPickup.id}_{user.uid}`, { // creates look up collection joining pickups and users (many to many => ) 
        pickupId: createdPickup.id, 
        userUid: user.uid,
        pickupDate: pickup.date,
        host: true
      })
    } catch (error) {
      console.log(error)
    }
  }
}